### ISSUE TITLE
Error with ExtractTextPlugin

### ISSUE THREAD

**Issue by monochrome-yeh** [tomasAlabes/stylefmt-loader#6]
```javascript
            {
                test: /\.scss$/,
                loader: mainCss.extract(
                    'style-loader',
                    [
                        'css?sourceMap',
                        'postcss',
                        'sass',
                        'stylefmt'
                    ],
                    {
                        publicPath: isProd ? '../' : '/assets/'
                    }
                ),
                exclude: /(node_modules|bower_components)/
            }

```

run webpack will get:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/Monochrome/Documents/xxx/xxx-com-v2/node_modules/stylefmt/lib/params.js:63:54
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/Monochrome/Documents/xxx/xxx-com-v2/node_modules/stylefmt/lib/params.js:63:54
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/Monochrome/Documents/xxx/xxx-com-v2/node_modules/stylefmt/lib/params.js:63:54
```

it seems doesn't support `ExtractTextPlugin`.

**Comment by tomasAlabes** [comment]
Thanks for reporting it :wink:
